name = "GeoIO"
uuid = "f5a160d5-e41d-4189-8b61-d57781c419e3"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "1.1.4"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoParquet = "e99870d8-ce00-4fdd-aeee-e09192881159"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
GslibIO = "4610876b-9b01-57c8-9ad9-06315f1a66a5"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArchGDAL = "0.10"
FileIO = "1.16"
GeoInterface = "1.0"
GeoJSON = "0.7"
GeoParquet = "0.1, 0.2"
GeoTables = "1.7"
GslibIO = "1.4"
ImageIO = "0.6"
Meshes = "0.35"
PlyIO = "1.1"
PrecompileTools = "1.2"
Shapefile = "0.10"
Tables = "1.7"
julia = "1.9"
